In [1]:
from imblearn.over_sampling import SMOTE #This is for SMOTE
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split,cross_val_score, GridSearchCV, RepeatedStratifiedKFold
from sklearn.preprocessing import MinMaxScaler
from sklearn.datasets import make_classification 
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report,roc_curve,roc_auc_score
# from catboost import CatBoostClassifier
import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.ensemble import GradientBoostingClassifier, AdaBoostClassifier, RandomForestClassifier
# from xgboost import XGBClassifier
import pickle

In [40]:
df= pd.read_excel('C:\\Users\\ayodh\\OneDrive\\Desktop\\Research\\Code\\Final.xlsx')

In [41]:
df

,Date,beans,carrot,cabbage,tomattos,brinjal,pumpkin,snake gourd,temp_max,temp_min,humidity,Area,Prod
0,2016-AUG-1,122,100,70,54,60,70,58,34.3,26.2,64.10,61.800000,865
1,2016-AUG-2,97,82,65,35,52,60,46,33.2,26.7,62.40,261.652197,2177
2,2016-AUG-3,87,84,72,27,60,48,34,33.8,26.7,60.19,155.010000,1050
3,2016-AUG-4,105,74,59,26,59,35,33,33.1,26.1,64.62,234.981000,2949
4,2016-SEP-1,112,74,61,27,59,33,33,33.9,27.7,61.14,170.598948,1254
...,...,...,...,...,...,...,...,...,...,...,...,...,...
111,2018-NOV-4,148,227,112,248,124,46,113,25.2,24.1,95.45,209.100000,2229
112,2018-DEC-1,139,224,94,197,113,45,85,26.4,24.6,92.21,98.281505,911
113,2018-DEC-2,177,205,100,278,107,39,89,27.9,24.9,88.13,80.590000,648
114,2018-DEC-3,107,125,90,117,69,32,69,28.3,24.8,83.50,335.730000,2185
115,2018-DEC-4,106,123,84,116,66,31,68,28.4,25.1,82.25,476.413500,4245

In [42]:
corr = df.corr()
corr.style.background_gradient(cmap ='coolwarm')

In [43]:
df.columns

Index(['Date', 'beans', 'carrot', 'cabbage', 'tomattos', 'brinjal', 'pumpkin',
       'snake gourd', 'temp_max', 'temp_min', 'humidity', 'Area', 'Prod'],
      dtype='object')

In [44]:
#Splitting the dataset in to x and y
x=df.drop(['Date','Prod','beans', 'carrot', 'cabbage', 'tomattos', 'brinjal', 'pumpkin',
       'snake gourd'], axis=1)
y=df['Prod']

In [45]:
x

     temp_max  temp_min  humidity        Area
0        34.3      26.2     64.10   61.800000
1        33.2      26.7     62.40  261.652197
2        33.8      26.7     60.19  155.010000
3        33.1      26.1     64.62  234.981000
4        33.9      27.7     61.14  170.598948
..        ...       ...       ...         ...
111      25.2      24.1     95.45  209.100000
112      26.4      24.6     92.21   98.281505
113      27.9      24.9     88.13   80.590000
114      28.3      24.8     83.50  335.730000
115      28.4      25.1     82.25  476.413500

[116 rows x 4 columns]

In [46]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
# regressor = RandomForestRegressor(n_estimator = 10, random_state = 0)
from sklearn.ensemble import RandomForestRegressor
 
 # create regressor object
regressor = RandomForestRegressor(n_estimators = 100, random_state = 0)
 
# fit the regressor with x and y data
regressor.fit(x, y)

RandomForestRegressor(random_state=0)

In [47]:
parameters = {'depth'         : [4,5,6,7,8,9, 10],'learning_rate' : [0.01,0.02,0.03,0.04],'iterations'    : [10, 20,30,40,50,60,70,80,90, 100] }
Grid_CBC = GridSearchCV(estimator=regressor, param_grid = parameters, cv = 5, n_jobs=-1)

In [48]:
# fit the regressor with x and y data
regressor.fit(x, y) # Fitting Random Forest Regression to the dataset
# import the regressor

RandomForestRegressor(random_state=0)

In [49]:
y_pred=regressor.predict(x_test)

In [50]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test,y_pred)

2773474.0423166696

In [51]:
param_grid = {  'bootstrap': [True], 'max_depth': [5, 10, None], 'max_features': ['auto', 'log2'], 'n_estimators': [5, 6, 7, 8, 9, 10, 11, 12, 13, 15]}

In [52]:
rfr = RandomForestRegressor(random_state = 1)

In [53]:
g_search = GridSearchCV(estimator = rfr, param_grid = param_grid, 

                          cv = 3, n_jobs = 1, verbose = 0, return_train_score=True)

In [54]:
g_search.fit(x_train, y_train);
print(g_search.best_params_)

{'bootstrap': True, 'max_depth': 5, 'max_features': 'auto', 'n_estimators': 7}

In [55]:
print(g_search.score(x_test, y_test))

0.9784525625194009